audio:
  f_max: 20000
  f_min: 20
  hop_length: 512
  hop_size_ms: 10
  midi_sample_rate: 100
  n_fft: 2048
  n_mels: 128
  noise_level_range:
  - 0.0
  - 0.01
  pitch_shift_range:
  - -2
  - 2
  sample_rate: 44100
  time_stretch_range:
  - 0.95
  - 1.05
  use_augmentation: true
  window_size_ms: 25
audio_config:
  f_max: 20000
  f_min: 20
  hop_length: 512
  n_fft: 2048
  n_mels: 229
batch_size: 1
data_dir: data/synthetic
description: Basic CNN-LSTM model for drum transcription
early_stopping_patience: 5
grad_clip_value: 1.0
inference:
  batch_size: 1
  checkpoint_path: best_model.pt
  device: cuda
  evaluate: true
  min_gap_ms: 10
  onset_threshold: 0.5
  save_midi: true
  save_predictions: true
  save_visualizations: false
  tolerance_ms: 50.0
learning_rate: 0.001
midi_sample_rate: 100
mixed_precision: true
model:
  encoder:
    base_channels: 16
    dropout: 0.2
    input_channels: 1
    kernel_sizes:
    - 7
    - 5
    - 3
    - 3
    paddings:
    - 3
    - 2
    - 1
    - 1
    strides:
    - 2
    - 2
    - 1
    - 1
  learning_rate: 0.001
  model_name: cnn_lstm
  onset_loss_weight: 1.0
  onset_positive_weight: 5.0
  temporal:
    dropout: 0.2
    hidden_dim: 256
    num_layers: 2
  velocity_loss_weight: 0.5
  weight_decay: 1.0e-05
model_config:
  bidirectional: true
  dropout: 0.3
  hidden_size: 256
  input_channels: 1
  input_size: 229
  num_layers: 2
model_name: drum_transcription_basic
num_epochs: 10
onset_loss_weight: 1.0
onset_positive_weight: 5.0
sample_length: 5.0
sample_rate: 44100
save_interval: 1
training:
  batch_size: 32
  checkpoint_dir: ./checkpoints
  dataset_path: ./data
  device: cuda
  early_stopping_patience: 10
  grad_clip_value: 1.0
  learning_rate: 0.001
  log_dir: ./logs
  mixed_precision: true
  num_epochs: 100
  num_workers: 4
  sample_length: 5.0
  seed: 42
  test_split: 0.1
  use_wandb: false
  val_split: 0.1
  wandb_project: drum-transcription
  weight_decay: 1.0e-05
use_wandb: false
velocity_loss_weight: 0.5
weight_decay: 1.0e-05
